const FullVNFields = [
    "title",
    "description",
    "rating",
    "votecount",
    "length_minutes",
    "length_votes",
    "aliases",
    "developers.name",
    "image.id",
    "image.url",
    "image.sexual",
    "image.violence",
    "image.thumbnail",
    "image.thumbnail_dims",
    "tags.id",
    "tags.rating",
    "tags.name",
    "tags.spoiler",
    "tags.category",
    "screenshots.thumbnail",
    "screenshots.thumbnail_dims",
    "screenshots.sexual",
    "screenshots.violence",
    "screenshots.release.title",
    "relations.relation",
    "relations.relation_official",
    "relations.title",
].join(",");

const CoverVNFields = ["title", "image.url", "image.sexual", "image.violence", "image.thumbnail",
    "image.thumbnail_dims"].join(
        ","
    );

const FullReleaseFields = [
    "id",
    "title",
    "alttitle",
    "languages.lang",
    "languages.title",
    "languages.latin",
    "producers.name",
    "platforms",
    "released",
    "minage",
    "patch",
    "official",
    "voiced",
    "resolution",
    "freeware",
    "uncensored",
    "has_ero",
    "notes",
    "media.medium",
    "media.qty",
    "vns.rtype",
    "vns.title",
    "vns.developers.name",
    "gtin",
    "catalog",
    "extlinks.url",
    "extlinks.label",
    "images.id",
    "images.type",
    "images.url",
    "images.sexual",
    "images.violence",
    "images.thumbnail",
    "images.thumbnail_dims",
].join(",");


export { FullVNFields, CoverVNFields, FullReleaseFields }
